# vim:fileencoding=utf-8:foldmethod=marker

# Docs in https://sw.kovidgoyal.net/kitty/conf/

font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0
cursor_shape underline

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

shell @HOME@/.nix-profile/bin/zsh
# macos_titlebar_color background

# jump to beginning and end of word
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

map cmd+enter new_window_with_cwd

background_opacity 0.95
background_blur 32
dynamic_background_opacity yes
window_padding_width 4

# BEGIN_KITTY_THEME
# Adapta Nokto Maia
include current-theme.conf
# END_KITTY_THEME
