# Application bindings
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
# bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Todoist, exec, omarchy-launch-or-focus ^todoist "uwsm-app -- Applications/Todoist.AppImage"
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password
bindd = SUPER SHIFT, E, Emacs, exec, omarchy-launch-or-focus ^emacs$ "uwsm-app -- emacs"

bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, W, Browser, exec, omarchy-launch-or-focus google-chrome
bindd = SUPER SHIFT, K, Mattermost, exec, omarchy-launch-or-focus-webapp Mattermost "https://mm.jedi.dev/"

bindd = SUPER SHIFT, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, X, Terminal, exec, omarchy-launch-or-focus kitty

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

bindd = SUPER, RETURN, Swap focused window with master, layoutmsg, swapwithmaster auto

# Override Omarchy's built-in binding to point to custom script
unbind = SUPER, L
bindd = SUPER, L, Change workspace layout, exec, hyprland-workspace-layout-cycle
