# Generated by ./update.sh - do not update manually!
# Last updated: 2026-02-27
{
  version = "9.26.4";
  x86_64-linux = {
    url = "https://electron-dl.todoist.net/linux/Todoist-linux-9.26.4-x86_64-latest.AppImage";
    hash = "sha256-zzRUU/ZLwoBRILFEHShjy8GOpww/spDVQM/EehjRNwY=";
  };
  aarch64-linux = {
    url = "https://electron-dl.todoist.net/linux/Todoist-linux-9.26.4-arm64-latest.AppImage";
    hash = "sha256-Ga7SKiWhusIMmojQ/3kxEkvpHvmYcSyIU3qlmX8uwh8=";
  };
}
