# Generated by ./update.sh - do not update manually!
# Last updated: 2026-03-08
{
  version = "6.1.0";
  x86_64-linux = {
    url = "https://github.com/mattermost/desktop/releases/download/v6.1.0/mattermost-desktop-6.1.0-linux-x86_64.AppImage";
    hash = "sha256-Dx62hDQp46n5Wv6V1zwRApPuHDyPnwCXwl154Gparew=";
  };
  aarch64-linux = {
    url = "https://github.com/mattermost/desktop/releases/download/v6.1.0/mattermost-desktop-6.1.0-linux-arm64.AppImage";
    hash = "sha256-AwGR/AZa0opVvE4ns2NaPH4HQw0Cp+gyaX6qAG60L3Y=";
  };
}
