# Generated by ./update.sh - do not update manually!
# Last updated: 2026-04-08
{
  version = "6.1.1";
  x86_64-linux = {
    url = "https://github.com/mattermost/desktop/releases/download/v6.1.1/mattermost-desktop-6.1.1-linux-x86_64.AppImage";
    hash = "sha256-Oxv7Crwb2OcTz9+d1jgX0j7HQktUhFGHErPlx6y7L2M=";
  };
  aarch64-linux = {
    url = "https://github.com/mattermost/desktop/releases/download/v6.1.1/mattermost-desktop-6.1.1-linux-arm64.AppImage";
    hash = "sha256-njlSHjLnSWbxN9PrMIM+xvlOQWoZwKBsJupuDSki+Q8=";
  };
}
