#!/usr/bin/env nix-shell
#! nix-shell -i bash --pure --keep GITHUB_TOKEN -p nix git curl cacert nix-prefetch-git gnugrep jq

set -euo pipefail
cd "$(dirname "$0")"

version=$(curl -s https://api.github.com/repos/mattermost/desktop/releases/latest | jq -r '.tag_name' | sed 's/^v//')

url=()
hash=()

for arch in x86_64 arm64
do
    current_url="https://github.com/mattermost/desktop/releases/download/v${version}/mattermost-desktop-${version}-linux-${arch}.AppImage"
    url+=($current_url)
    hash+=("$(nix --extra-experimental-features nix-command hash convert --hash-algo sha256 --to sri $(nix-prefetch-url $current_url))")
done

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{
  version = "$version";
  x86_64-linux = {
    url = "${url[0]}";
    hash = "${hash[0]}";
  };
  aarch64-linux = {
    url = "${url[1]}";
    hash = "${hash[1]}";
  };
}
EOF

echo "Updated to Mattermost Desktop $version"
